on: [push, pull_request]
jobs:
  check-norm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install norminette
          norminette
          make
